services:
  app:
    build:
      context: .
      args:
        - VITE_API_URL=
    container_name: codejam-service
    # network_mode: host 를 추가합니다.
    network_mode: host
    # host 모드에서는 ports 설정이 필요 없거나 무시되지만 명시적으로 두어도 무방합니다.
    environment:
      - PORT=3000
      - REDIS_HOST=10.0.2.6
      - REDIS_PORT=6379
    restart: always